# Generated by Django 5.0.1 on 2024-02-17 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetoone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='adress',
            new_name='address',
        ),
    ]
