# Generated by Django 5.0.1 on 2024-02-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coments',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
