# Generated by Django 5.0.1 on 2024-02-09 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_coments_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coments',
            new_name='Coment',
        ),
    ]
